[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
byte-unit = "5"
clap = { version = "4.5", features = ["derive"]}
color-eyre = "0.6"
env_logger = "0.11"
git2 = "0.19"
log = "0.4"

